---
name: concourse

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: councourse
  instances: 1
  vm_type: large
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: (( external_url ))

      # replace with username/password, or configure GitHub auth
      basic_auth_username: admin
      basic_auth_password: (( basic_auth_password ))

      # replace with your SSL cert and key
      tls_cert: ((atc_ssl.certificate))
      tls_key: ((atc_ssl.private_key))

      postgresql_database: &atc_db atc
  - name: tsa
    release: concourse
    properties: {}
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: REPLACE_ME
        password: ((postgres_password))
